[build]
  command = "npm install --legacy-peer-deps && npm run build --legacy-peer-deps"
  functions = "netlify/functions"
  publish = "dist"

  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
